/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cristo_messenger;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.ListSelectionModel;
import javax.swing.SwingUtilities;

/**
 *
 * @author Lenovo
 */
public class Segunda_ventana extends javax.swing.JFrame {

    /**
     * Creates new form Segunda_ventana
     */
    public Segunda_ventana() throws SQLException {
        
        registro_con = new User_Controller();
        
        chat_con = new Friends_Controller();
        chat_array_friends = new ArrayList();
        
        setExtendedState(MAXIMIZED_BOTH);
        initComponents();
        
        //Registro
        user = " ";
        name = " ";
        pass = " ";
        sur1 = " ";
        sur2 = " ";
        
        //Chat_imagen
        ImageIcon fot = new ImageIcon("imagenes/logo.jpg");
        Icon icono = new ImageIcon(fot.getImage().getScaledInstance(miImagen.getWidth(), miImagen.getHeight(), Image.SCALE_DEFAULT));
        miImagen.setIcon(icono);
        this.repaint();
        
        ImageIcon foto = new ImageIcon("imagenes/logo.jpg");
        Icon icono2 = new ImageIcon(foto.getImage().getScaledInstance(label_imagen_amigo.getWidth(), label_imagen_amigo.getHeight(), Image.SCALE_DEFAULT));
        label_imagen_amigo.setIcon(icono2);
        this.repaint();
        
        ImageIcon foto1 = new ImageIcon("imagenes/logo.jpg");
        Icon icono3 = new ImageIcon(foto1.getImage().getScaledInstance(label_imagen_user.getWidth(), label_imagen_user.getHeight(), Image.SCALE_DEFAULT));
        label_imagen_user.setIcon(icono3);
        this.repaint();
        
        //Chat_friends
        listModel = new DefaultListModel();
        this.list_friends.setModel(listModel);
        this.list_friends.setSelectionMode(ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        //Chat friends mensajes
        mess_con = new  Message_Controller ();
        mess_mod = new ArrayList <Message_Model>();
        
        
        //Chat_friends_cambiar_pantalla_mensajes
        mouseListener = new MouseAdapter() {
        public void mouseClicked(MouseEvent mouseEvent) {
          JList theList = (JList) mouseEvent.getSource();
          if (mouseEvent.getClickCount() == 2) {
            int index = theList.locationToIndex(mouseEvent.getPoint());
            if (index >= 0) {
              Object o = theList.getModel().getElementAt(index);
              System.out.println("Double-clicked on: " + o.toString());
              label_amigo.setText(o.toString());
              friend_mess = o.toString();
              String user_activo_label = label_usuario_activo.getText();
//              get_messages(mess_mod,user_activo_label,friend_mess);
              
              //Poner los mensajes anteriores 
              //1Traerme todos los mensajes
              
              //2Insertarlos
//              this.text_area.append(this.label_usuario_activo.getText()+": "+texto+"\n");

            }
          }
        }
      };
      list_friends.addMouseListener(mouseListener);
        

    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pestañas = new javax.swing.JTabbedPane();
        panel_chat = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        text = new javax.swing.JTextArea();
        label_usuario_activo = new javax.swing.JLabel();
        boton_envio_mensajes = new javax.swing.JButton();
        miImagen = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        list_friends = new javax.swing.JList<>();
        label_amigo = new javax.swing.JLabel();
        label_imagen_amigo = new javax.swing.JLabel();
        label_imagen_user = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        text_area = new javax.swing.JTextArea();
        panel_registro = new javax.swing.JPanel();
        label_user = new javax.swing.JLabel();
        lable_name = new javax.swing.JLabel();
        lable_pass = new javax.swing.JLabel();
        lable_sur1 = new javax.swing.JLabel();
        lable_sur2 = new javax.swing.JLabel();
        text_user = new javax.swing.JTextField();
        text_name = new javax.swing.JTextField();
        text_pass = new javax.swing.JTextField();
        text_sur1 = new javax.swing.JTextField();
        text_sur2 = new javax.swing.JTextField();
        label_registro = new javax.swing.JLabel();
        button_next = new javax.swing.JButton();
        panel_debug = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        text.setColumns(20);
        text.setRows(5);
        text.setText("Aqui van los mensajes\n");
        jScrollPane2.setViewportView(text);

        label_usuario_activo.setText("Aqui va el usuario activo");

        boton_envio_mensajes.setText(">>");
        boton_envio_mensajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_envio_mensajesActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(list_friends);

        label_amigo.setText("Aqui va el amigo con el que habla");

        text_area.setEditable(false);
        text_area.setColumns(20);
        text_area.setRows(5);
        jScrollPane1.setViewportView(text_area);

        javax.swing.GroupLayout panel_chatLayout = new javax.swing.GroupLayout(panel_chat);
        panel_chat.setLayout(panel_chatLayout);
        panel_chatLayout.setHorizontalGroup(
            panel_chatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_chatLayout.createSequentialGroup()
                .addGroup(panel_chatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_chatLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                        .addGroup(panel_chatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_chatLayout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(boton_envio_mensajes))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_chatLayout.createSequentialGroup()
                                .addComponent(label_imagen_amigo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(label_amigo)
                                .addGap(35, 35, 35))
                            .addComponent(jScrollPane1)))
                    .addGroup(panel_chatLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(miImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label_imagen_user, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(label_usuario_activo)
                        .addGap(1, 1, 1)))
                .addGap(42, 42, 42))
        );
        panel_chatLayout.setVerticalGroup(
            panel_chatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_chatLayout.createSequentialGroup()
                .addGroup(panel_chatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_chatLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panel_chatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_usuario_activo)
                            .addComponent(miImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(label_imagen_user, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panel_chatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_chatLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(label_amigo)
                        .addGap(38, 38, 38)
                        .addGroup(panel_chatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_chatLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(panel_chatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(boton_envio_mensajes, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel_chatLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(label_imagen_amigo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pestañas.addTab("CHAT", panel_chat);

        panel_registro.setBackground(new java.awt.Color(251, 225, 251));

        label_user.setText("User:");

        lable_name.setText("Name:");

        lable_pass.setText("Password:");

        lable_sur1.setText("Surname1: ");

        lable_sur2.setText("Surname2:");

        text_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_userActionPerformed(evt);
            }
        });

        text_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_nameActionPerformed(evt);
            }
        });

        text_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_passActionPerformed(evt);
            }
        });

        text_sur2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_sur2ActionPerformed(evt);
            }
        });

        label_registro.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        label_registro.setForeground(new java.awt.Color(102, 0, 102));
        label_registro.setText("REGISTRO");

        button_next.setBackground(new java.awt.Color(102, 0, 102));
        button_next.setForeground(new java.awt.Color(255, 51, 255));
        button_next.setText("NEXT");
        button_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_nextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_registroLayout = new javax.swing.GroupLayout(panel_registro);
        panel_registro.setLayout(panel_registroLayout);
        panel_registroLayout.setHorizontalGroup(
            panel_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_registroLayout.createSequentialGroup()
                .addGroup(panel_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_registroLayout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addGroup(panel_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_user)
                            .addComponent(lable_sur1)
                            .addComponent(lable_sur2)
                            .addComponent(lable_name)
                            .addComponent(lable_pass))
                        .addGap(125, 125, 125)
                        .addGroup(panel_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panel_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(text_pass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(panel_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(text_user, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(text_sur2)))
                            .addComponent(text_name, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text_sur1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel_registroLayout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(label_registro))
                    .addGroup(panel_registroLayout.createSequentialGroup()
                        .addGap(273, 273, 273)
                        .addComponent(button_next)))
                .addContainerGap(516, Short.MAX_VALUE))
        );
        panel_registroLayout.setVerticalGroup(
            panel_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_registroLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(panel_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_registroLayout.createSequentialGroup()
                        .addComponent(label_registro)
                        .addGap(41, 41, 41)
                        .addComponent(label_user))
                    .addComponent(text_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(panel_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(text_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lable_pass))
                .addGap(47, 47, 47)
                .addGroup(panel_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lable_name)
                    .addComponent(text_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(text_sur1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lable_sur1))
                .addGap(18, 18, 18)
                .addGroup(panel_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(text_sur2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lable_sur2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 201, Short.MAX_VALUE)
                .addComponent(button_next)
                .addGap(43, 43, 43))
        );

        pestañas.addTab("REGISTRO", null, panel_registro, "");

        javax.swing.GroupLayout panel_debugLayout = new javax.swing.GroupLayout(panel_debug);
        panel_debug.setLayout(panel_debugLayout);
        panel_debugLayout.setHorizontalGroup(
            panel_debugLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1069, Short.MAX_VALUE)
        );
        panel_debugLayout.setVerticalGroup(
            panel_debugLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 583, Short.MAX_VALUE)
        );

        pestañas.addTab("DEBUG", panel_debug);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pestañas)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(pestañas)
                .addContainerGap())
        );

        pestañas.getAccessibleContext().setAccessibleName("REGISTRO");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void text_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_userActionPerformed
        
    }//GEN-LAST:event_text_userActionPerformed

    private void text_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_nameActionPerformed
        
    }//GEN-LAST:event_text_nameActionPerformed

    private void text_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_passActionPerformed
        
    }//GEN-LAST:event_text_passActionPerformed
    
    private void text_sur2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_sur2ActionPerformed
       
    }//GEN-LAST:event_text_sur2ActionPerformed

    private void button_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_nextActionPerformed
        //REGISTRO//
        boolean check = true; //En principio existe el user
        
        if (this.text_user.getText().isEmpty() || this.text_name.getText().isEmpty() || this.text_pass.getText().isEmpty() || text_sur1.getText().isEmpty() || this.text_sur2.getText().isEmpty() ){
             JOptionPane.showMessageDialog(null, "Acceso denegado:\n"
                + "Por favor rellene todos los datos", "Acceso denegado",
                JOptionPane.ERROR_MESSAGE);
        }else{
            //Copio datos
            this.user=this.text_user.getText();
            this.name=this.text_name.getText();
            this.pass=this.text_pass.getText();
            this.sur1=this.text_sur1.getText();
            this.sur2=this.text_sur2.getText();
            System.out.println(user);
            
            check=this.registro_con.check_user_id(user);
        
            if (check == true) { //Exite
                JOptionPane.showMessageDialog(null, "Acceso denegado:\n"
                    + "Por favor ingrese un usuario que no exista", "Acceso denegado",
                    JOptionPane.ERROR_MESSAGE);

            } else { 
                try {
                //No existe, se agrega a la bd
                    System.out.println("DEBUG: INSERT (VISTA)");
                    this.registro_con.agregar_user (user,name,pass,sur1,sur2);

                    System.out.println("DEBUG: TERMINADO INSERT (VISTA)");

                } catch (SQLException ex) {
                    Logger.getLogger(Segunda_ventana.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        }
        
    }//GEN-LAST:event_button_nextActionPerformed

    private void boton_envio_mensajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_envio_mensajesActionPerformed
        String texto;
        
        texto = this.text.getText();
        
        this.text_area.append(this.label_usuario_activo.getText()+": "+texto+"\n");
        this.text.setText("");
        
    }//GEN-LAST:event_boton_envio_mensajesActionPerformed

    public void getFriends () {
        
        String user =this.label_usuario_activo.getText();
        this.chat_con.get_all_friends_con(chat_array_friends, user);
        
        
        for (int i = 0; i<this.chat_array_friends.size(); i++) { 
            listModel.addElement(this.chat_array_friends.get(i));
        }
        this.list_friends.setModel(listModel);

    }
    
    public void get_messages(ArrayList mess, String user_orig, String user_dest) {
//        mess_con.get_messages(mess, user_orig, user_dest);
//        
//        for (int i =0; i<mess.size(); i++) {
//            
////            if (mess.get(i).getId_user_orig() == user_orig){
//////                this.text_area.append(this.label_usuario_activo.getText()+": "+texto+"\n");
////            }
//        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Segunda_ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Segunda_ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Segunda_ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Segunda_ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Segunda_ventana().setVisible(true);
                    
                } catch (SQLException ex) {
                    Logger.getLogger(Segunda_ventana.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_envio_mensajes;
    private javax.swing.JButton button_next;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel label_amigo;
    private javax.swing.JLabel label_imagen_amigo;
    private javax.swing.JLabel label_imagen_user;
    private javax.swing.JLabel label_registro;
    private javax.swing.JLabel label_user;
    public javax.swing.JLabel label_usuario_activo;
    private javax.swing.JLabel lable_name;
    private javax.swing.JLabel lable_pass;
    private javax.swing.JLabel lable_sur1;
    private javax.swing.JLabel lable_sur2;
    private javax.swing.JList<String> list_friends;
    private javax.swing.JLabel miImagen;
    private javax.swing.JPanel panel_chat;
    private javax.swing.JPanel panel_debug;
    private javax.swing.JPanel panel_registro;
    private javax.swing.JTabbedPane pestañas;
    private javax.swing.JTextArea text;
    private javax.swing.JTextArea text_area;
    private javax.swing.JTextField text_name;
    private javax.swing.JTextField text_pass;
    private javax.swing.JTextField text_sur1;
    private javax.swing.JTextField text_sur2;
    private javax.swing.JTextField text_user;
    // End of variables declaration//GEN-END:variables
       
    /*Registro*/
    private User_Controller registro_con;
    private String user;
    private String name;
    private String pass;
    private String sur1;
    private String sur2;
    
    /*Chat*/
    public String user_act;
    private Friends_Controller chat_con;
    ArrayList chat_array_friends;
    DefaultListModel listModel;
    String [] listData;
    MouseListener mouseListener;
    private Message_Controller mess_con;
    ArrayList <Message_Model> mess_mod;
    String friend_mess;

}
